export type RandomLocationInterface = {
  city: string;
  country: string;
  countryCode: string;
  phoneCode: string;
  postalCode: string;
  street: string;
};

export const RANDOM_LOCATION_LIST: RandomLocationInterface[] = [
  {
    city: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    phoneCode: '+31',
    postalCode: '1011AB',
    street: 'Damrak',
  },
  {
    city: 'Andorra la Vella',
    country: 'Andorra',
    countryCode: 'AD',
    phoneCode: '+376',
    postalCode: 'AD500',
    street: 'Avinguda Meritxell',
  },
  { city: 'Athens', country: 'Greece', countryCode: 'GR', phoneCode: '+30', postalCode: '10552', street: 'Ermou' },
  {
    city: 'Belgrade',
    country: 'Serbia',
    countryCode: 'RS',
    phoneCode: '+381',
    postalCode: '11000',
    street: 'Knez Mihailova',
  },
  {
    city: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    phoneCode: '+49',
    postalCode: '10117',
    street: 'Unter den Linden',
  },
  {
    city: 'Bern',
    country: 'Switzerland',
    countryCode: 'CH',
    phoneCode: '+41',
    postalCode: '3000',
    street: 'Marktgasse',
  },
  {
    city: 'Bratislava',
    country: 'Slovakia',
    countryCode: 'SK',
    phoneCode: '+421',
    postalCode: '81101',
    street: 'Obchodná',
  },
  {
    city: 'Brussels',
    country: 'Belgium',
    countryCode: 'BE',
    phoneCode: '+32',
    postalCode: '1000',
    street: 'Rue de la Loi',
  },
  {
    city: 'Bucharest',
    country: 'Romania',
    countryCode: 'RO',
    phoneCode: '+40',
    postalCode: '010011',
    street: 'Calea Victoriei',
  },
  {
    city: 'Budapest',
    country: 'Hungary',
    countryCode: 'HU',
    phoneCode: '+36',
    postalCode: '1051',
    street: 'Andrássy út',
  },
  {
    city: 'Chisinau',
    country: 'Moldova',
    countryCode: 'MD',
    phoneCode: '+373',
    postalCode: '2012',
    street: 'Strada Ștefan cel Mare',
  },
  {
    city: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    phoneCode: '+45',
    postalCode: '1000',
    street: 'Strøget',
  },
  {
    city: 'Dublin',
    country: 'Ireland',
    countryCode: 'IE',
    phoneCode: '+353',
    postalCode: 'D02',
    street: 'O’Connell Street',
  },
  {
    city: 'Helsinki',
    country: 'Finland',
    countryCode: 'FI',
    phoneCode: '+358',
    postalCode: '00100',
    street: 'Esplanadi',
  },
  {
    city: 'Kiev',
    country: 'Ukraine',
    countryCode: 'UA',
    phoneCode: '+380',
    postalCode: '01001',
    street: 'Khreshchatyk',
  },
  {
    city: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    phoneCode: '+351',
    postalCode: '1100-123',
    street: 'Rua Augusta',
  },
  {
    city: 'Ljubljana',
    country: 'Slovenia',
    countryCode: 'SI',
    phoneCode: '+386',
    postalCode: '1000',
    street: 'Slovenska cesta',
  },
  {
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    phoneCode: '+44',
    postalCode: 'SW1A 1AA',
    street: 'Downing Street',
  },
  {
    city: 'Luxembourg',
    country: 'Luxembourg',
    countryCode: 'LU',
    phoneCode: '+352',
    postalCode: 'L-1111',
    street: 'Rue du Saint-Esprit',
  },
  { city: 'Madrid', country: 'Spain', countryCode: 'ES', phoneCode: '+34', postalCode: '28013', street: 'Gran Vía' },
  {
    city: 'Minsk',
    country: 'Belarus',
    countryCode: 'BY',
    phoneCode: '+375',
    postalCode: '220030',
    street: 'Prospekt Nezavisimosti',
  },
  {
    city: 'Monaco',
    country: 'Monaco',
    countryCode: 'MC',
    phoneCode: '+377',
    postalCode: '98000',
    street: 'Boulevard de la Condamine',
  },
  { city: 'Moscow', country: 'Russia', countryCode: 'RU', phoneCode: '+7', postalCode: '101000', street: 'Tverskaya' },
  {
    city: 'Nicosia',
    country: 'Cyprus',
    countryCode: 'CY',
    phoneCode: '+357',
    postalCode: '1016',
    street: 'Ledra Street',
  },
  {
    city: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    phoneCode: '+47',
    postalCode: '0150',
    street: 'Karl Johans gate',
  },
  {
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    phoneCode: '+33',
    postalCode: '75001',
    street: 'Rue de Rivoli',
  },
  {
    city: 'Podgorica',
    country: 'Montenegro',
    countryCode: 'ME',
    phoneCode: '+382',
    postalCode: '81000',
    street: 'Ulica Slobode',
  },
  {
    city: 'Prague',
    country: 'Czech Republic',
    countryCode: 'CZ',
    phoneCode: '+420',
    postalCode: '11000',
    street: 'Na Příkopě',
  },
  {
    city: 'Reykjavik',
    country: 'Iceland',
    countryCode: 'IS',
    phoneCode: '+354',
    postalCode: '101',
    street: 'Laugavegur',
  },
  {
    city: 'Riga',
    country: 'Latvia',
    countryCode: 'LV',
    phoneCode: '+371',
    postalCode: 'LV-1050',
    street: 'Brīvības iela',
  },
  { city: 'Rome', country: 'Italy', countryCode: 'IT', phoneCode: '+39', postalCode: '00100', street: 'Via del Corso' },
  {
    city: 'San Marino',
    country: 'San Marino',
    countryCode: 'SM',
    phoneCode: '+378',
    postalCode: '47890',
    street: 'Via Giuseppe Garibaldi',
  },
  {
    city: 'Sarajevo',
    country: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    phoneCode: '+387',
    postalCode: '71000',
    street: 'Ferhadija',
  },
  {
    city: 'Skopje',
    country: 'North Macedonia',
    countryCode: 'MK',
    phoneCode: '+389',
    postalCode: '1000',
    street: 'Macedonia Street',
  },
  {
    city: 'Sofia',
    country: 'Bulgaria',
    countryCode: 'BG',
    phoneCode: '+359',
    postalCode: '1000',
    street: 'Vitosha Boulevard',
  },
  {
    city: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    phoneCode: '+46',
    postalCode: '111 22',
    street: 'Drottninggatan',
  },
  { city: 'Tallinn', country: 'Estonia', countryCode: 'EE', phoneCode: '+372', postalCode: '10111', street: 'Viru' },
  {
    city: 'Tbilisi',
    country: 'Georgia',
    countryCode: 'GE',
    phoneCode: '+995',
    postalCode: '0105',
    street: 'Rustaveli Avenue',
  },
  {
    city: 'Tirana',
    country: 'Albania',
    countryCode: 'AL',
    phoneCode: '+355',
    postalCode: '1001',
    street: 'Rruga e Kavajës',
  },
  {
    city: 'Vaduz',
    country: 'Liechtenstein',
    countryCode: 'LI',
    phoneCode: '+423',
    postalCode: '9490',
    street: 'Städtle',
  },
  {
    city: 'Valletta',
    country: 'Malta',
    countryCode: 'MT',
    phoneCode: '+356',
    postalCode: 'VLT 1111',
    street: 'Republic Street',
  },
  {
    city: 'Vatican City',
    country: 'Vatican City',
    countryCode: 'VA',
    phoneCode: '+379',
    postalCode: '00120',
    street: 'Via della Conciliazione',
  },
  {
    city: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    phoneCode: '+43',
    postalCode: '1010',
    street: 'Kärntner Straße',
  },
  {
    city: 'Vilnius',
    country: 'Lithuania',
    countryCode: 'LT',
    phoneCode: '+370',
    postalCode: '01100',
    street: 'Gedimino pr.',
  },
  {
    city: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    phoneCode: '+48',
    postalCode: '00-001',
    street: 'Nowy Świat',
  },
  {
    city: 'Yerevan',
    country: 'Armenia',
    countryCode: 'AM',
    phoneCode: '+374',
    postalCode: '0010',
    street: 'Abovyan Street',
  },
  { city: 'Zagreb', country: 'Croatia', countryCode: 'HR', phoneCode: '+385', postalCode: '10000', street: 'Ilica' },
];
